// Generated by CoffeeScript 2.0.2
(function() {
  var DiscordEvents, DiscordJs, Helpers, RustEvents, WebRcon, debugChannel, discord, discordClient, helpers, rustChannel, wRcon;

  DiscordJs = require('discord.js');

  WebRcon = require('webrconjs');

  DiscordEvents = require('./lib/discord-events.coffee');

  RustEvents = require('./lib/rust-events.coffee');

  Helpers = require('./lib/helpers.coffee');

  discord = null;

  helpers = null;

  debugChannel = null;

  rustChannel = null;

  discordClient = function(token) {
    discord = new DiscordJs.Client();
    discord.login(token).catch(console.error);
    return discord.on('ready', function() {
      console.log('Connected to Discord Server');
      debugChannel = discord.channels.find('name', 'debug');
      rustChannel = discord.channels.find('name', 'rust-server');
      helpers = new Helpers();
      wRcon(process.env.RUST_IP, process.env.RUST_PORT, process.env.RUST_PASSWORD);
      return new DiscordEvents(discord);
    });
  };

  wRcon = function(rustip, rustport, password) {
    wRcon = new WebRcon(rustip, 'rustport');
    wRcon.connect(password);
    return new RustEvents(wRcon, helpers, discord);
  };

  discordClient(process.env.DISCORD_TOKEN);

}).call(this);

//# sourceMappingURL=main.js.map
