// Generated by CoffeeScript 2.0.2
(function() {
  var Helpers;

  Helpers = (function() {
    var reoccuringErrors;

    class Helpers {
      constructor() {}

      errorNotification(error, channel) {
        if (reoccuringErrors > 10) {
          process.exit(1);
        }
        console.log(error);
        return channel.send(error).then(reoccuringErrors++);
      }

    };

    reoccuringErrors = 0;

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);

//# sourceMappingURL=helpers.js.map
