// Generated by CoffeeScript 2.0.2
(function() {
  var RustEvents;

  RustEvents = class RustEvents {
    constructor(wRcon, helpers, discord) {
      var debugChannel;
      debugChannel = discord.channels.find('name', 'debug');
      wRcon.on('connect', function() {
        return console.log('Connected to Rust Server');
      });
      wRcon.on('disconnect', function() {
        return helpers.errorNotification('Disconnected from Rust Server', debugChannel);
      });
      wRcon.on('error', function(err) {
        return helpers.errorNotification(`wRcon ${err}`, debugChannel);
      });
      wRcon.on('message', function(msg) {
        var playerJoin;
        if (msg.message.includes('has entered the game')) {
          playerJoin = msg.message.replace(/\[.*\]/, '');
          return rustChannel.fetchMessage(rustChannel.lastMessageID).then(function(message) {
            var rustJoin;
            if (playerJoin !== message.content) {
              rustChannel.send(playerJoin);
              rustJoin = playerJoin.replace('entered', 'joined');
              return wRcon.run('say ' + rustJoin, 0);
            }
          }).catch((function(error) {
            return helpers.errorNotification(error, debugChannel);
          }));
        } else {
          return console.log(msg.message);
        }
      });
    }

  };

  module.exports = RustEvents;

}).call(this);

//# sourceMappingURL=rust-events.js.map
